version: "3.5"

services:
    postgres:
        container_name: postgres_cda_burger
        image: postgres:16.2
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-burger}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-burger}
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - "5437:5432"
        restart: unless-stopped

volumes:
    postgres:
    pgadmin:
